Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-21.04"
  config.vm.network :forwarded_port, guest: 443, host: 8443
  config.vm.network :forwarded_port, guest: 80, host: 4567

  config.vm.synced_folder "./unseals", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main
    sudo apt update 
    sudo apt install - y ufw mc screen vault
    echo "VAULT_ADDR=http://127.0.0.1:8200" >> /etc/environment
    echo "VAULT_TOKEN='root'" >> /etc/environment
    echo "" >> /var/log/vault.log
    ufw allow 22 && ufw allow 443 && ufw enable
  SHELL
 
  config.vm.provision "shell", run: "always",  inline: <<-SHELL
     screen -dmS scr001 bash -c 'vault server -dev -dev-root-token-id root'; exec bash
  SHELL

  config.vm.provision "shell", path: "./unseals/vault_dev_ca_auth.sh", run: "always"
  config.vm.provision "shell", run: "always",  inline: <<-SHELL
     sudo systemctl restart nginx
  SHELL
end
